export const ADMIN_VIEW_TITLES: Record<string, string> = {
  dashboard: 'Dashboard',
  organizations: 'Organizations',
  recruiters: 'Recruiters',
  candidates: 'Candidates',
  jobs: 'Jobs',
  applications: 'Applications',
  revenue: 'Revenue & Payments',
  subscriptions: 'Subscriptions',
  credits: 'Credits',
  'billing-management': 'Billing Management',
  support: 'Support Desk',
  moderation: 'Moderation',
  announcements: 'Announcements',
  'feature-flags': 'Feature Flags',
  'platform-analytics': 'Platform Analytics',
  'ai-monitoring': 'AI Monitoring',
  'system-monitoring': 'System Monitoring',
  notifications: 'Notifications',
  emails: 'Email Center',
  'audit-logs': 'Audit Logs',
  'platform-settings': 'Platform Settings',
  'developer-tools': 'Developer Tools',
  'data-export': 'Data Export',
  permissions: 'Roles & Permissions',
  'global-search': 'Global Search',
};
